account/urls.py
from django.urls import path
from .views import LoginView,LogoutView
urlpatterns = [
    path('',LoginView.as_view(),name='login_page'),
    path('',LogoutView.as_view(),name = 'logout')
]

manager/urls.py
from django.urls import path
from .views import (ManagerIndexView,AddDepartmentView,
                    ListOfDepartmentView,BatchView,AddInstructorView,
                    ListOfInstructors,AddCourseView,BatchYearUpdate,
                    RemoveBatchView,RemovePost,UpdateDepartmentView,
                    RemoveDepartmentConfirmationView,RemoveDepartmentView,
                    PeriodTimeView,AddStudentView,
                    RoomView,UpdateRoomView,AddSemesterView,
                    ListOfSemsterView,AddStudentView,ListOfStudentView,
                    UpdateSemsterView
                    )
urlpatterns = [
    path('manager-index/',ManagerIndexView.as_view(),name = 'manager_index'),
    path('add-department/',AddDepartmentView.as_view(),name = 'add_department'),
    path('list-of-department/',ListOfDepartmentView.as_view(),name = 'list_of_department'),
    path('batch/',BatchView.as_view(),name = 'batch'),
    path('add-instructor/',AddInstructorView.as_view(),name = 'add_instructor'),
    path('instructor-list/',ListOfInstructors.as_view(),name = 'instructor_list'),
    path('add-course/',AddCourseView.as_view(),name='add_course'),
    path('update-batch/<str:pk>/',BatchYearUpdate.as_view(),name='update_batch'),
    path('remove-batch/<str:pk>/',RemoveBatchView.as_view(),name ='remove_batch'),
    path('remove-batch-post/',RemovePost.as_view(),name='remove_post'),
    path('update-department/<str:pk>/',UpdateDepartmentView.as_view(),name = 'update_departemnt'),
    path('remove-confirmation-department/<str:pk>/',RemoveDepartmentConfirmationView.as_view(),name = 'remove_confirmation_department'),
    path('remove-department/',RemoveDepartmentView.as_view(),name = 'remove_department'),
    path('period-time/',PeriodTimeView.as_view(),name ='period_time'),
    path('add-student/',AddStudentView.as_view(),name = 'add_student'),
    path('room/',RoomView.as_view(),name='room'),
    path('update-room/<str:pk>',UpdateRoomView.as_view(),name = 'update_room'),
    path('add-semster/',AddSemesterView.as_view(),name = 'add_semster'),
    path('list-of-semster/',ListOfSemsterView.as_view(),name = 'list_of_semster'),
    path('list-of-student/',ListOfStudentView.as_view(),name = 'list_of_student'),
    path('update-semster/<str:pk>/',UpdateSemsterView.as_view(),name = 'update_semster')
]

student_attendance_management_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('',include('manager.urls')),
]


manager/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Department(models.Model):
    department_name = models.CharField(max_length=225)
    description = models.TextField()
    department_register_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    is_visible = models.BooleanField(default=True)
    def __str__(self):
        return self.department_name
class Batch(models.Model):
    year = models.IntegerField()
    is_visible = models.BooleanField(default=True)
    def str(self) -> str:
        return str(self.year)
class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ManyToManyField(Department, blank=True, null=True)
    phone_no = models.CharField(max_length=10, blank=True, null=True)
    def str(self) -> str:
        return self.user.first_name
class Semester(models.Model):
    semster_number = models.IntegerField(null=True,blank=True)
    batch = models.ForeignKey(Batch,on_delete=models.PROTECT,null=True,blank=True)
    starting_date = models.DateField(null=True,blank=True)
    is_visible = models.BooleanField(default=True)
    end_date = models.DateField(null=True,blank=True)    
class Course(models.Model):
    name = models.TextField()
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester,on_delete=models.PROTECT,null=True,blank=True)
    code = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    def str(self) -> str:
        return "{0} ({1})".format(self.name, self.code)
class PeriodTime(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()
    def __str__(self):
        return f"{self.start_time} - {self.end_time}"
class Room(models.Model):
    room_no = models.CharField(max_length=50)
    Building  = models.CharField(max_length=50,null=True,blank=True)
    def str(self) -> str:
        return self.room_no
class Period(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_exam = models.BooleanField(default=False)
    time = models.ForeignKey(PeriodTime, on_delete=models.CASCADE)
    day = models.IntegerField(blank=True, null=True)
    campus = models.CharField(max_length=100)
    room = models.ForeignKey(Room, blank=True, null=True, on_delete=models.CASCADE)
    def str(self) -> str:
        return self.room.room_no
    def isCurrentClass(self):
        print('dd ', self.day, datetime.date.today().isoweekday())
        check_time = timezone.localtime(timezone.now()).time()
        st = self.time.start_time
        et = self.time.end_time
        if not self.day == datetime.date.today().isoweekday(): return False
        if st < et:
            return check_time >= st and check_time <= et
        else: # crosses midnight
            return check_time >= st or check_time <= et
    def isUpComingClass(self):
        time = timezone.localtime(timezone.now())
        return (not self.isCurrentClass()) and (self.day ==  datetime.date.today().isoweekday()) and (self.time.start_time > time.time())
class TimeTable(models.Model):
    periods = models.ManyToManyField(Period)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    version = models.IntegerField(default=1)
    semster = models.ForeignKey(Semester,models.PROTECT,null=True,blank=True)
    def str(self) -> str:
        return "Semester {0} (v{1})".format(self.semester.semster_number, self.version)
class Section(models.Model):
    batch = models.ForeignKey(Batch,on_delete=models.PROTECT)
    department = models.ForeignKey(Department, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)
    devision = models.CharField(choices=(
        ('Regular', 'Regular'),
        ('Extension', 'Extension')
    ), max_length=50,null=True,blank=True)
    time_table = models.OneToOneField(TimeTable, on_delete=models.CASCADE, blank=True, null=True)
    def str(self) -> str:
        return "{0} - {1} - {2}".format(
            self.department.name,
            self.batch,
            self.name
        )

manager/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib import messages
from .models import Department,Batch,Course,Instructor,PeriodTime,Section,Room,Semester
from django.contrib.auth.models import User,Group
from student.models import Student
import re
class ManagerIndexView(View):
    def get(self,request):
        number_of_department = Department.objects.count()
        number_of_instructors = Instructor.objects.count()
        number_of_courses = Course.objects.count()
        context ={'number_of_department':number_of_department,'number_of_instructors':number_of_instructors,'number_of_courses':number_of_courses}
        return render(request,'manager_templates/manager_index.html',context)
class AddDepartmentView(View):
    def get(self,request):
        return render(request,'manager_templates/add_department.html')
    def post(self,request):
        department_name = request.POST.get('department_name')
        description = request.POST.get('description')
        department_name_filter = Department.objects.filter(department_name=department_name).count()
        if not department_name:
            messages.error(request,'Department name can not be null')
            request.session['form_data'] = {'department_name': department_name, 'description': description} 
            return redirect('add_department')
        if not description:
            messages.error(request,'Description name can not be null') 
            return redirect('add_department')
        if department_name_filter >=1:
            messages.error(request,'this department already registered') 
            return redirect('add_department')
        else:
            department = Department(department_name=department_name,description=description)
            department.save()
            messages.success(request,'Department Registerd successfully')
            return redirect('list_of_department')
class ListOfDepartmentView(View):
    def get(self,request):
        list_of_department = Department.objects.filter(is_visible=True)
        context = {'list_of_department':list_of_department}
        return render(request,'manager_templates/list_of_department.html',context)
class BatchView(View):
    def get(self,request):
        batches = Batch.objects.filter(is_visible=True)
        context = {'batches':batches}
        return render(request,'manager_templates/batch.html',context) 
    def post(self,request):
        year = request.POST.get('year')
        year_filter = Batch.objects.filter(year=year)
        if not year:
            messages.error(request,'Year is Required') 
            return redirect('batch')
        if year_filter.exists():
            messages.error(request,'This Year is alrread Registered') 
            return redirect('batch')
        else:
            batch = Batch.objects.create(year=year)
            messages.success(request,'Year saved successfully')
            return redirect('batch')
            
            
class AddInstructorView(View):
    def get(self, request):
        departments = Department.objects.all().order_by('department_name')
        context = {'departments': departments}
        return render(request, 'manager_templates/add_instructor.html', context)

    def post(self, request):
        form_data = {
            'username': request.POST.get('username', ''),
            'first_name': request.POST.get('first_name', ''),
            'last_name': request.POST.get('last_name', ''),
            'email': request.POST.get('email', ''),
            'phone_number': request.POST.get('phone_number', ''),
            'password': request.POST.get('password'),
            'confirm_password': request.POST.get('confirm_password'),
            'department': request.POST.getlist('department', []),
        }

        name_regex = r"^[A-Za-z\-'/\\]+$"
        username_regex = r"^\w+$"
        email_regex = r"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"
        print("=============================",len(form_data['phone_number']))
        # if len(form_data['phone_number'] >10):
        #     messages.error(request,'Phone number length should be 10 numbers')
        #     return redirect('add_instructor')
        if not form_data['department']:
            messages.error(request, 'Department is Required')
            return redirect('add_instructor')
        if not re.match(name_regex, form_data['first_name']):
            messages.error(request, "Please enter a valid first name using only letters.")
        if not re.match(name_regex, form_data['last_name']):
            messages.error(request, "Please enter a valid last name with only letters.")
        if not re.match(email_regex, form_data['email']):
            messages.error(request, "Invalid email format. Please enter a valid email address.")
        if User.objects.filter(email=form_data['email']).exists():
            messages.error(request, "This email is already associated with an existing account.")
        if form_data['password'] != form_data['confirm_password']:
            messages.error(request, "Password and Confirm Password should be the same.")
        if len(form_data['password']) < 8:
            messages.error(request, "Password must be at least 8 characters long.")
        if not re.match(username_regex, form_data['username']):
            messages.error(request, "Please enter a valid username.")
        if User.objects.filter(username=form_data['username']).exists():
            messages.error(request, "Username is already taken.")
        if any(messages.get_messages(request)):
            departments = Department.objects.all()
            context = {'departments': departments, 'form_data': form_data}
            return render(request, 'manager_templates/add_instructor.html', context)
        else:
            user = User.objects.create(username=form_data['username'], first_name=form_data['first_name'], last_name=form_data['last_name'], email=form_data['email'])
            user.set_password(form_data['password'])
            group = Group.objects.get(name='Instructor')
            user.groups.add(group)
            user.save() 
            instructor = Instructor.objects.create(user=user, phone_no=form_data['phone_number'])
            instructor.department.set(form_data['department'])  # Use set() for many-to-many field
            messages.success(request, "Instructor Saved Successfully")
            return redirect('add_instructor')
            
class ListOfInstructors(View):
    def get(self,request):
        instructors = Instructor.objects.all()
        context = {'instructors':instructors}   
        return render(request,'manager_templates/list_of_instructors.html',context)    
class AddCourseView(View):
    def get(self, request):
        instructors = Instructor.objects.all()  
        courses = Course.objects.all()
        semsters = Semester.objects.filter(is_visible=True)
        context = {'instructors': instructors, 'courses': courses,'semsters':semsters}
        return render(request, 'manager_templates/course.html', context)

    def post(self, request):
        course_name = request.POST.get('course_name')
        course_code = request.POST.get('course_code')
        instructor_id = request.POST.get('Instructor')
        semster_id = request.POST.get('semster')
        if not course_code:
            messages.error(request, 'Course code is required')
            return redirect('add_course')
        if not course_name:
            messages.error(request, 'Course name is required')
            return redirect('add_course')
        if not instructor_id:
            messages.error(request, 'Instructor is required')
            return redirect('add_course')
        if not semster_id:
            messages.error(request,"Semster is Required")
            return redirect('add_course')
        try:
            instructor_get = Instructor.objects.get(pk=instructor_id)  # Fetch instructor by primary key
            semster_get = Semester.objects.get(id = semster_id)
        except Instructor.DoesNotExist:
            messages.error(request, 'Instructor does not exist')
            return redirect('add_course')
        if Course.objects.filter(code=course_code).exists():
            messages.error(request, 'This course code is already taken by another course')
            return redirect('add_course')

        course = Course.objects.create(name=course_name, code=course_code, instructor=instructor_get,semester=semster_get)
        messages.success(request, 'Course added successfully')
        return redirect('add_course')
class BatchYearUpdate(View):
    def get(self,request,pk):
        select_batch = Batch.objects.get(id = pk)
        context = {'select_batch':select_batch}
        return render(request,'manager_templates/update_batch.html',context)
    def post(self,request,pk):
        year = request.POST.get('year')
        select_batch = Batch.objects.get(id=pk)
        if not year:
            messages.error(request,'Year is required')
            return redirect('update_batch')
        select_batch.year = year    
        select_batch.save()
        messages.success(request,'Batch updated successfully')
        return redirect('batch')    
class RemoveBatchView(View):
    def get(self,request,pk):
       select_batch = Batch.objects.get(id=pk) 
       context = {'select_batch':select_batch}
       return render(request,'manager_templates/remove_batch.html',context)
class RemovePost(View):
    def post(self,request):
        batch_id = request.POST.get('batch_id')
        select_batch = Batch.objects.get(id = batch_id) 
        select_batch.is_visible = False
        select_batch.save()
        messages.success(request,'Batch Removed successfully')
        return redirect('batch')        

manager/templates/manager_templates/add_department.html
{% extends "manager_templates/base_manager.html" %}
{% block content %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Add Departments</h1>
    
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">

                <div class="card" style="margin-top: 20px;">
                    <div class="card-body">
                        <!-- <h5 class="card-title text-center">Add Department</h5> -->
                        <div class="mb-3">
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <div style="text-align: center"
                                    class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}"
                                    style="white-space: pre-line">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </ul>
                            </div>
                            {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <!-- <label for="last-name" class="form-label">Host Address</label> -->
                                <input type="text" name="department_name" value="{{department_name}}" class="form-control"  
                                    placeholder="Department Name" style="margin-top: 20px;" />
                            </div>
                            <div class="form-floating mb-3">
                                <textarea class="form-control" placeholder="Leave a comment here" value="{{description}}" id="floatingTextarea2" style="height: 100px"
                                 name="description"></textarea>
                                <label for="floatingTextarea2">Description</label>
                            </div>
                            <div class="mb-3">
                                <button type="submit" name="action" value="give_access" class="btn btn-success" id="give-access">
                                    <i class="bi bi-floppy"></i> 
                                    <span>Submit</span>
                                </button>
                            </div>
                        </form>

                    </div>
                </div>

            </div>

            
            </div>
        </div>
    

</main><!-- End #main -->
{% endblock %}

manager/templates/manager_templates/course.html
{% extends "manager_templates/base_manager.html" %}
{% block content %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Add Course</h1>

    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">

            <div class="card" style="margin-top: 20px;">
                <div class="card-body">
                    <!-- <h5 class="card-title text-center">Add Department</h5> -->
                    <div class="mb-3">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <div style="text-align: center"
                                class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}"
                                style="white-space: pre-line">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="course_name" value="{{course_name}}" class="form-control"
                                placeholder="Course Name" style="margin-top: 20px;" />
                        </div>
                        <div class="mb-3">
                            <input type="text" name="course_code" value="{{course_code}}" class="form-control" placeholder="Course Code"
                                style="margin-top: 20px;" />
                        </div>
                        <div class="mb-3">
                            <select name="Instructor" class="form-select" id="database-users-select">
                                <option disabled selected>Select Instructor Name</option>
                                {% for instructor in instructors %}
                                <option value="{{instructor.id}}">{{instructor.user.first_name}} {{instructor.user.last_name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <select name="semster" class="form-select" id="database-users-select">
                                <option disabled selected>Select Semster</option>
                                {% for semster in semsters %}
                                <option value="{{semster.id}}">Semster({{semster.semster_number}}) Batch({{semster.batch.year}})</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <button type="submit" name="action" value="give_access" class="btn btn-success"
                                id="give-access">
                                <i class="bi bi-floppy"></i>
                                <span>Submit</span>
                            </button>
                        </div>
                    </form>

                </div>
            </div>

        </div>


    </div>
    </div>
    <div class="pagetitle">
        <h1>List Of Batch</h1>
    
    </div><!-- End Page Title -->
    
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card bg-glass">
                {% if message_error %}
                <div style="text-align: center" class="alert alert-danger" style="white-space: pre-line">
                    {{ message_error}}
                </div>
                {% elif message_succ %}
                <div style="text-align: center" class="alert alert-success" style="white-space: pre-line">
                    {{ message_succ }}
                </div>
                {% endif %}
            </div>
    
        </div>
        <div class="card-body">
            <p class="card-title"></p>
            <div class="table-responsive">
                <table class="table table-hover" id="dataTables-example" width="50%">
                    <thead>
                        <tr style="font-weight: normal; font-size: smaller;">
                            <th>Course Code</th>
                            <th>Course Name</th>
                            <th>Instructor</th>
                            <th>Semster</th>
                            <th>Course Registered Date</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in courses %}
                        <tr>  
                            <td>{{course.code}}</td>
                            <td>{{course.name}}</td>
                            <td>{{course.instructor.user.username}}</td>
                            <td>Semster({{course.semester.semster_number}}) Batch({{course.semester.batch.year}})</td>
                            <td>{{course.created_at}}</td>
                            <td><a href="#" class="btn btn-outline-info btn-rounded"><i class="bi bi-pencil-square"></i></a>
                            </td>
                            <td><a href="#" class="btn btn-outline-danger btn-rounded"><i class="bi bi-trash3"></i></a>
                            </td>
                        </tr>
                       {% endfor %}
                    </tbody>
    
                </table>
            </div>
        </div>
    
    </div>
    </div>



</main><!-- End #main -->
{% endblock %}

manager/templates/manager_templates/update_instructor.html
{% extends "manager_templates/base_manager.html" %}
{% block content %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Update Instructor</h1>

    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">

            <div class="card" style="margin-top: 20px;">
                <div class="card-body">
                    <!-- <h5 class="card-title text-center">Add Department</h5> -->
                    <div class="mb-3">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <div style="text-align: center"
                                class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}"
                                style="white-space: pre-line">
                                {{ message }}
                            </div>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="username" value="{{ select_user.username }}" class="form-control"
                                placeholder="Username" style="margin-top: 20px;" />
                            <!-- Display username error message -->
                            {% if messages and 'username' in messages %}
                            <p class="text-danger">{{ messages.username }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <input type="text" name="first_name" value="{{ select_user.first_name }}" class="form-control"
                                placeholder="First Name" style="margin-top: 20px;" />
                            <!-- Display first name error message -->
                            {% if messages and 'first_name' in messages %}
                            <p class="text-danger">{{ messages.first_name }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <input type="text" name="last_name" value="{{ select_user.last_name }}" class="form-control"
                                placeholder="Last Name" style="margin-top: 20px;" />
                            <!-- Display last name error message -->
                            {% if messages and 'last_name' in messages %}
                            <p class="text-danger">{{ messages.last_name }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <input type="text" name="email" value="{{ select_user.email }}" class="form-control"
                                placeholder="Email" style="margin-top: 20px;" />
                            <!-- Display email error message -->
                            {% if messages and 'email' in messages %}
                            <p class="text-danger">{{ messages.email }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <!-- <label for="last-name" class="form-label">Host Address</label> -->
                            <input type="text" name="phone_number" value="{{select_user.phone_number}}"
                                class="form-control" placeholder="Phone Number" style="margin-top: 20px;" />
                        </div>
                        <div class="mb-3">
                            <label for="">Department</label><br>
                            <select name="department" id="id_department" class="form-control" multiple>
                                {% for department in departments %}
                                <option value="{{department.id}}">{{department.department_name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password" value="{{form_data.password}}" class="form-control"
                                placeholder="Password" style="margin-top: 20px;" />

                            {% if messages and 'password' in messages %}
                            <p class="text-danger">{{ messages.password }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <input type="password" name="confirm_password" value="{{form_data.confirm_password}}"
                                class="form-control" placeholder="Confirm Password" style="margin-top: 20px;" />
                            <!-- Display confirm password error message -->
                            {% if messages and 'confirm_password' in messages %}
                            <p class="text-danger">{{ messages.confirm_password }}</p>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <button type="submit" name="action" value="give_access" class="btn btn-success"
                                id="give-access">
                                <i class="bi bi-floppy"></i>
                                <span>Add Instructor</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>
{% endblock %}